
networks:
  default:
    name: "${INTERNAL_NETWORK}"

services:
  calibre:
    image: "lscr.io/linuxserver/calibre:${CALIBRE_VERSION}"
    container_name: calibre
    # security_opt:
    #   - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kyiv
      - "PASSWORD=${CALIBRE_PASSWORD}" #optional
      - "CUSTOM_USER=${CALIBRE_USER}"
      # - CLI_ARGS= #optional
    volumes:
      - "./data/calibre/config:/config"
    ports:
      - "${CALIBRE_GUI_PORT}:8080"
      - "${CALIBRE_GUI_HTTPS_PORT}:8181"
      - "${CALIBRE_WEB_PORT}:8081"
    restart: unless-stopped

