# version: "3.8"

networks:
  default:
    name: "${INTERNAL_NETWORK}"
    attachable: true
    ipam:
     config:
       - subnet: "${SUBNET_AND_MASK}"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - "./data/qbittorrent/config:/config"
      - "~/Downloads/:/downloads" #optional
      - "~/Videos/:/videos" #optional
    ports:
      - "${WEBUI_PORT}:8080"
      - "${TORRENTING_PORT}:6881"
      - "${TORRENTING_PORT}:6881/udp"
    restart: unless-stopped

