
networks:
  default:
    name: "${INTERNAL_NETWORK}"

services:
  prometheus:
    image: "prom/prometheus:${PROMETHEUS_VERSION}"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "${PROMETHEUS_PORT}:9090"
    restart: unless-stopped
    volumes:
      - "./data/prometheus/config:/etc/prometheus"
      - "./data/prometheus/data:/prometheus"

  node_exporter:
    image: "quay.io/prometheus/node-exporter:${PROMETHEUS_NODE_VERSION}"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
    pid: host
    restart: unless-stopped
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
