# version: "3.8"

services:
  dummy:
    image: alpine
    command: "true"

networks:
  default:
    name: "${INTERNAL_NETWORK}"
    attachable: true
    ipam:
     config:
       - subnet: "${SUBNET_AND_MASK}"



