networks:
  default:
    name: "${INTERNAL_NETWORK}"

services:
  nextcloud:
    image: "nextcloud:${NEXTCLOUD_VERSION}"
    environment:
      - "POSTGRES_DB=${NEXTCLOUD_PG_DB}"
      - "POSTGRES_USER=${NEXTCLOUD_PG_USER}"
      - "POSTGRES_PASSWORD=${NEXTCLOUD_PG_PASSWORD}"
      - "POSTGRES_HOST=${POSTGRES_HOST}:${POSTGRES_PORT}"
      - "NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USR}"
      - "NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}"
      - "NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}"
    volumes:
      - "./data/nextcloud/data:/var/www/html"
    ports:
      - "${NEXTCLOUD_WEB_PORT}:80"
    restart: always

