
networks:
  default:  
    name: "${INTERNAL_NETWORK}"

services:
  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    container_name: "${POSTGRES_HOST}"
    restart: "always"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - "./data/postgres/data:/var/lib/postgresql/data"

