
networks:
  default:
    name: "${INTERNAL_NETWORK}"

services:
  trilium:
    image: "triliumnext/notes:${TRILIUM_VERSION}"
    restart: unless-stopped
    ports:
      - "${TRILIUM_PORT}:8080"
    environment:
      - "TRILIUM_DATA_DIR=/home/node/trilium-data"
    volumes:
      - "./data/trilium/data:/home/node/trilium-data"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
