networks:
  default:
    name: "${INTERNAL_NETWORK}"

services:
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    container_name: owncloud_server
    restart: always
    ports:
      - ${OWNCLOUD_WEB_PORT}:8080
    depends_on:
      # - redis
      - valkey
    environment:
      # - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_TRUSTED_DOMAINS=${OWNCLOUD_TRUSTED_DOMAINS}
      - OWNCLOUD_DB_TYPE=postgres
      - OWNCLOUD_DB_NAME=${OWNCLOUD_PG_DB}
      - OWNCLOUD_DB_USERNAME=${OWNCLOUD_PG_USER}
      - OWNCLOUD_DB_PASSWORD=${OWNCLOUD_PG_PASSWORD}
      - OWNCLOUD_DB_HOST=${POSTGRES_HOST}:${POSTGRES_PORT}
      - OWNCLOUD_ADMIN_USERNAME=${OWNCLOUD_ADMIN_USR}
      - OWNCLOUD_ADMIN_PASSWORD=${OWNCLOUD_ADMIN_PASSWORD}
      # - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=${OWNCLOUD_REDIS_HOST}
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - "./data/owncloud/data:/mnt/data"



  valkey:
    image: valkey/valkey:${OWNCLOUD_VALKEY}
    container_name: owncloud_valkey

    volumes:
      - "./data/owncloud_valkey/data:/data"
