# version: "3.8"

networks:
  default:  
    # external: true
    name: "${INTERNAL_NETWORK}"

services:
  synapse:
    image: "matrixdotorg/synapse:${MATRIX_SYNAPSE_VERSION}"
    restart: "unless-stopped"
    environment:
      SYNAPSE_SERVER_NAME: "${DOMAIN_NAME}"
      SYNAPSE_REPORT_STATS: "${SYNAPSE_REPORT_STATS}"
      SYNAPSE_HTTP_PORT: ${SYNAPSE_HTTP_PORT}
      SYNAPSE_CONFIG_DIR: "${SYNAPSE_CONFIG_DIR}"
      SYNAPSE_CONFIG_PATH: "/data/homeserver.yaml"
      UID: "1000"
      GID: "1000"
      TZ: "Europe/London"
    volumes:
      - "./data/matrix/synapse:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.synapse.loadbalancer.server.port=${SYNAPSE_HTTP_PORT}"
      - "traefik.http.routers.synapse.rule=Host(`synapse.${DOMAIN_NAME}`)"
      - "traefik.http.routers.synapse.entrypoints=web-secure"
      - "traefik.http.routers.synapse.tls.certresolver=letsencrypt"

  nginx:
    image: "nginx:${MATRIX_NGINX_VERSION}"
    restart: "unless-stopped"
    volumes:
      - "./data/matrix/nginx/matrix.conf:/etc/nginx/conf.d/matrix.conf"
      - ./data/matrix/nginx/www:/var/www/
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.matrix.loadbalancer.server.port=80"
      - "traefik.http.routers.matrix.rule=Host(`matrix.${DOMAIN_NAME}`) || Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.matrix.entrypoints=web-secure"
      - "traefik.http.routers.matrix.tls.certresolver=letsencrypt"

  # riot:
  #   image: "bubuntux/riot-web:${MATRIX_RIOT_VERSION}"
  #   restart: "unless-stopped"
  #   volumes:
  #     - "./data/matrix/riot/config.json:/etc/riot-web/config.json:ro"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.services.riot.loadbalancer.server.port=80"
  #     - "traefik.http.routers.riot.rule=Host(`riot.${DOMAIN_NAME}`)"
  #     - "traefik.http.routers.riot.entrypoints=web-secure"
  #     - "traefik.http.routers.riot.tls.certresolver=letsencrypt"
  #     - "traefik.http.routers.riot.middlewares=allowframe@file"
      
  # coturn:
  #   image: "instrumentisto/coturn:${MATRIX_COTURN_VERSION}"
  #   restart: "unless-stopped"
  #   volumes:
  #     - "./data/matrix/coturn/turnserver.conf:/etc/coturn/turnserver.conf"
  #   ports:
  #     - "49160-49200:49160-49200/udp"
  #     - "3478:3478"
  #     - "5349:5349"
  #
