# version: "3.8"

networks:
  default:
    name: "${INTERNAL_NETWORK}"
    attachable: true
    ipam:
     config:
       - subnet: "${SUBNET_AND_MASK}"

services:
  qbittorrent:
    image: "lscr.io/linuxserver/qbittorrent:${QBITTORRENT_VERSION}"
    container_name: qbittorrent
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Etc/UTC"
      - "WEBUI_PORT=${WEBUI_PORT}"
      - "TORRENTING_PORT=${TORRENTING_PORT}"
    volumes:
      - "./data/qbittorrent/config:/config"
      - "~/Downloads/:/downloads" #optional
      - "~/Videos/:/downloads/videos" #optional
    ports:
      - "${WEBUI_PORT}:${WEBUI_PORT}"
      - "${TORRENTING_PORT}:${TORRENTING_PORT}"
      - "${TORRENTING_PORT}:${TORRENTING_PORT}/udp"
    restart: unless-stopped

