CREATE ROLE ${MATRIX_POSTGRES_USER};
ALTER ROLE ${MATRIX_POSTGRES_USER} WITH PASSWORD '${MATRIX_DB_ROLE_PASSWORD}';
ALTER ROLE ${MATRIX_POSTGRES_USER} WITH LOGIN;
CREATE DATABASE ${MATRIX_POSTGRES_DB} ENCODING 'UTF8' LC_COLLATE='C' LC_CTYPE='C' template=template0 OWNER ${MATRIX_POSTGRES_USER};
GRANT ALL PRIVILEGES ON DATABASE ${MATRIX_POSTGRES_DB} TO ${MATRIX_POSTGRES_USER};

