http:
  routers:
    redirecttohttps:
      entryPoints:
        - "web"
      middlewares:
        - "httpsredirect"
      rule: "HostRegexp(`{host:.+}`)"
      service: "noop@internal"

    dashboard:
      rule: "Host(`traefik.${DOMAIN_NAME}`)"
      entryPoints:
        - "web-secure"
      tls:
        certresolver: "letsencrypt"
      service: "dashboard@internal"
      middlewares:
        - "basicauth"

    api:
      rule: "Host(`traefik.${DOMAIN_NAME}`) && PathPrefix(`/api`)"
      tls:
        certresolver: "letsencrypt"
      service: "api@internal"
      middlewares:
        - "basicauth"


