http:
  routers:
    redirecttohttps:
      entryPoints:
        - "web"
      middlewares:
        - "httpsredirect"
      rule: "HostRegexp(`{host:.+}`)"
      service: "noop@internal"

    dashbord:
      rule: "Host(`traefik.${DOMAIN_NAME}`)"
      service: "api@internal"
      middlewares:
        - "basicauth"
